ui/src/index.html
ui/src/style.css

Hi,
I made few visual changes to make the app looks a bit better.
- Center the pages with flex, to have a perfect horizontal and vertical centering,
- Adjust the different margin to make the page breathe a little more,
- Full review of the buttons style,
- Add emojis on the user mood choices,
- Review some font weights to avoid too much split.
- Keep a (small) margin on the page on mobile phones
- Handle the landscape mode with optimized scroll
- Have a minimal card width

:lipstick: Refresh the UI

---

ui/src/index.html
ui/src/index.ts

Closes #13 
Add a new errorUnknowUserPage with the email of the unknow user.
Displaying this specific error on the UI.

:children_crossing: add an error message when the user email is unknow to the app

---

ui/src/index.html
ui/src/style.css

Taken from faq.zenika.com
See #9

:lipstick: Add an animated loading indicator

---

functions/src/days-before-campaign-ends.test.ts
functions/src/days-before-campaign-ends.ts

Fix a bug : reminder email sent when the campaign starts

---

.circleci/config.yml
functions/src/cast-vote.ts
functions/src/config.ts
functions/src/exchange-token.ts
functions/src/update-stats.ts
functions/tsconfig.json
functions/tslint.json
ui/src/api.ts
ui/src/auth/firebase.ts
ui/src/auth/session-repository.ts
ui/tsconfig.json

:white_check_mark: Add format checking to circleci config

---

ui/src/index.html
ui/src/index.ts

:sparkles: Add home buttons

---

functions/src/cast-vote.ts
functions/src/config.ts
functions/src/import-votes.ts
functions/src/index.ts
functions/src/send-email-to-manager.ts

Import votes from JSON

---

firestore.rules
functions/src/compute-statistics.ts
functions/src/index.ts
functions/src/update-stats.ts
ui/src/index.html
ui/src/index.ts
ui/src/services/computeCampaignLabel.ts
ui/src/services/computeDataFromDataBase.ts
ui/src/services/renderTemplate.ts
ui/src/style.css

Code might not be the best but at least it works

:sparkles: Add location based stats

---

.circleci/config.yml

Fix prod deploy config

---

functions/src/import-employees-from-alibeez.ts
package-lock.json
package.json
ui/src/auth/auth0.ts
ui/src/index.html
ui/src/index.ts
ui/src/styles/navbar.css
ui/src/styles/style.css

:lipstick: Add navbar and harmonise UI

---

ui/src/index.html
ui/src/styles/style.css

Those styles were broken by #57.

:bug: fix style of vote buttons

---

functions/src/send-email-to-manager.ts

:recycle: Change value of vote in emails so it's more readable

---

functions/src/send-email-to-manager.ts

:sparkles: Remove vote value from mail sent to manager

---

functions/src/process-email-queue.ts

:sparkles: Remove email body once it's sent

---

functions/src/config.ts
functions/src/send-reminders.ts

:sparkles: Change reminders link

---

functions/src/config.ts
functions/src/import-employees-from-alibeez-daily.ts
functions/src/import-employees-from-alibeez.ts

See https://github.com/Zenika/humeur-du-mois-2018/issues/87

Employee import supports more than 500 employees

---

functions/src/cast-vote.ts
functions/src/send-email-to-manager.ts
ui/src/api.ts
ui/src/index.html
ui/src/index.ts
ui/src/styles/style.css

Add a simple textarea for comment

---

ui/src/index.html
ui/src/index.ts
ui/src/styles/style.css

Hi,
This PR is here to fix some issues with the hold message in the stats which looks completely different than the rest of the app.
It also fix spacing and sizes around the new comment field.

Fix stats holding message style and comment field style

---

functions/src/compose-email-html.test.ts
functions/src/compose-email-html.ts

Improve clarity of the email to the manager

---

functions/src/send-reminders.ts

:sparkles: replace text link in reminder email by html link

---

functions/src/import-employees-from-alibeez.ts

Proxybeez has been shutdown a while ago and Humeur du mois did not complain about it. This fixes the fact that Humeur does not complain when Alibeez/Proxybeez respond with an error.

:bug: fix alibeez error not reported

---

functions/src/import-employees-from-alibeez.ts
ui/src/index.ts

The user email provided by Auth0 and the user id provided by Alibeez may not use the exact same case, so a legitimate user may not be recognized by the app. This change fixes this.

🐛 relax user id matching

---

.circleci/config.yml

See https://github.com/Zenika/dreamlab/issues/205

💚 use new ci context

---

functions/src/send-reminders.ts

💄 only send end-of-campaign reminder to employees who have not voted yet

---

.circleci/config.yml

Because I completely messed up in #128.

💚 fix deployment

---

.circleci/config.yml
functions/package.json
package-lock.json
package.json

see #140 
There seems to be new emulators https://firebase.google.com/docs/rules/emulator-setup to help run things localy ?
We might have to look at it a little further in another PR

⬆️ Update firebase cli

---

.gitignore
README.md
functions/package-lock.json
package-lock.json
package.json
ui/package-lock.json
ui/package.json
ui/src/auth/auth0.ts
ui/src/auth/firebase.ts
ui/src/index.html
ui/src/index.ts

Closes #104 
After signing in, show a logout button which:
- log out of Firebase
- log out of auth0 (clear local storage)
- redirect to the auth0 sign in page

✨ Add logout

---

functions/src/import-employees-from-alibeez.ts

⚠ Alibeez key and URL in config must change.

👽 adapt to new proxybeez api

---

functions/src/cast-vote.ts
functions/src/generate-random-email-token.ts
functions/src/get-current-campaign-state.ts
functions/src/send-email-to-manager.ts
functions/src/send-reminders.ts
functions/src/stats-manager.ts

Some tokens are for voting (one per voter) and others are for fetching manager stats (multiple is fine). This is now explicit.

♻ make token type explicit

---

ui/package-lock.json
ui/package.json
ui/webpack.config.ts

Latest versions compatible with webpack v4.

⬆ bump ui webpack toolchain

---

functions/src/compose-email-to-manager.ts
functions/src/compose-reminder-email.ts
ui/src/styles/style.css

fix #212 
- Fix color of the selector on dark mode (orange outline).
- Fix color of the not that great (orange)

💄 Update dark mode selector and not great color
